[project]
name = "342-project-fellas-doin-multiplexing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "scipy>=1.15.3",
    "tqdm>=4.67.1",
]
